// Generated by CoffeeScript 1.3.3
(function() {

  requirejs.config({
    shim: {
      "lib/leaflet": {
        deps: ["jquery"],
        exports: "L"
      },
      "lib/jsbezier": {
        exports: "jsBezier"
      }
    },
    paths: {
      "jquery": "//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min"
    }
  });

  requirejs(["map/mapdisplay", "jquery"], function(MapDisplay) {
    return new MapDisplay($("#map"));
  });

}).call(this);
