// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["js/struct/events"], function(Events) {
    var Sidebar;
    return Sidebar = (function(_super) {

      __extends(Sidebar, _super);

      function Sidebar(el) {
        var _this = this;
        this.el = el;
        this.receiveData = __bind(this.receiveData, this);

        this.ul = $("ul", this.el);
        this.existingLis = {};
        $.ajax({
          url: "articleDetails.json",
          dataType: "json",
          success: function(data) {
            _this.data = data;
            return _this.trigger("loaded");
          }
        });
        Sidebar.__super__.constructor.call(this);
      }

      Sidebar.prototype.receiveData = function(data, obj) {
        var article, i, previ, target, _i, _len, _ref, _results;
        this.ul.empty();
        previ = -60;
        _ref = data.articleCounts;
        _results = [];
        for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
          article = _ref[i];
          target = this.existingLis[article[0]];
          if (!target) {
            data = this.data[article[0]];
            if (!data) {
              data = {
                title: article[0]
              };
            }
            target = $("<li><a href='" + article[0] + "'>" + data.title + "</a></li>");
          }
          previ += 60;
          target.css("top", previ);
          this.ul.append(target);
          if (i === 20) {
            break;
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      };

      return Sidebar;

    })(Events);
  });

}).call(this);
