// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define([], function() {
    var Events;
    return Events = (function() {

      function Events() {
        this.trigger = __bind(this.trigger, this);

        this.on = __bind(this.on, this);
        this.events = {};
      }

      Events.prototype.on = function(ev, func) {
        if (!this.events[ev]) {
          this.events[ev] = [];
        }
        return this.events[ev].push(func);
      };

      Events.prototype.trigger = function(ev, args) {
        var func, _i, _len, _ref, _results;
        _ref = this.events[ev];
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          func = _ref[_i];
          _results.push(func(args));
        }
        return _results;
      };

      return Events;

    })();
  });

}).call(this);
