// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define([], function() {
    var Coordinate;
    return Coordinate = (function() {

      function Coordinate(x, y) {
        this.x = x;
        this.y = y;
        this.distanceTo = __bind(this.distanceTo, this);

      }

      Coordinate.prototype.distanceTo = function(otherCoord) {
        var xs, ys;
        xs = 0;
        ys = 0;
        xs = otherCoord.x - this.x;
        xs = xs * xs;
        ys = otherCoord.y - this.y;
        ys = ys * ys;
        return Math.sqrt(xs + ys);
      };

      return Coordinate;

    })();
  });

}).call(this);
