// Generated by CoffeeScript 1.3.3
(function() {

  define(["jslib/leaflet", "./heatmaplayer"], function(leaflet, h) {
    var MapDisplay;
    return MapDisplay = (function() {

      function MapDisplay(target) {
        var sttileLayer, tileLayer,
          _this = this;
        this.mapEl = target;
        this.map = L.map(this.mapEl[0], {
          fadeAnimation: false,
          zoom: 2,
          center: [16.5, -3.2]
        });
        tileLayer = L.tileLayer('http://{s}.tiles.mapbox.com/v3/alastaircoote.map-n7irpmld/{z}/{x}/{y}.png', {
          maxZoom: 18
        });
        tileLayer.addTo(this.map);
        sttileLayer = L.tileLayer('http://{s}.tiles.mapbox.com/v3/alastaircoote.map-rjqv06av/{z}/{x}/{y}.png', {
          maxZoom: 18,
          zIndex: 100
        });
        sttileLayer.addTo(this.map);
        return;
        $.ajax({
          url: "commentdata/points.json",
          success: function(data) {
            var activeData, adjustedData, heat, points;
            points = JSON.parse(data);
            heat = new h({
              data: points
            });
            adjustedData = _this.adjustData(points);
            activeData = adjustedData;
            _this.map.addLayer(heat);
            heat.on("animationComplete", function() {
              if (activeData === points) {
                activeData = adjustedData;
              } else {
                activeData = points;
              }
              return heat.setData(activeData, 10000);
            });
            return heat.setData(adjustedData, 10000);
          }
        });
      }

      MapDisplay.prototype.adjustData = function(data) {
        return data.map(function(p) {
          return {
            lat: p.lat,
            lng: p.lng,
            val: p.val > 50 ? p.val - 50 : p.val + 50
          };
        });
      };

      return MapDisplay;

    })();
  });

}).call(this);
